# Generated by Django 4.2.7 on 2024-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique",),
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro_nue",),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo", "parametro_sq", "id"), name="unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=("protocolo_proceso", "muestras", "id"), name="unique_intro_nue"
            ),
        ),
    ]
