# Generated by Django 4.2.7 on 2024-12-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0003_remove_secuencias_unique_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="secuencias", name="unique",),
        migrations.RemoveConstraint(model_name="secuencias", name="unique_intro_nue",),
        migrations.AddField(
            model_name="secuencias",
            name="fecha_configuracion_protocolo_metodo",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha Configuracion Protocolo de Metodo",
            ),
        ),
        migrations.AddField(
            model_name="secuencias",
            name="fecha_configuracion_protocolo_proceso",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha Configuracion Protocolo de Proceso",
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=(
                    "protocolo",
                    "parametro_sq",
                    "fecha_configuracion_protocolo_metodo",
                ),
                name="unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="secuencias",
            constraint=models.UniqueConstraint(
                fields=(
                    "protocolo_proceso",
                    "muestras",
                    "fecha_configuracion_protocolo_proceso",
                ),
                name="unique_intro_nue",
            ),
        ),
    ]
